package backend;

import flixel.system.FlxAssets.FlxShader;
import haxe.macro.Expr;
import haxe.rtti.Meta;

/**
 * BgfxShaderManager — Maps flixel shaders to bgfx programs.
 *
 * Extracts GLSL source from flixel shader metadata (@:glFragmentSource,
 * @:glVertexSource, @:glFragmentHeader, @:glVertexHeader), converts
 * to bgfx-compatible format (replacing OpenFL-specific uniforms with
 * bgfx equivalents), and creates bgfx program handles.
 *
 * When pre-compiled .bin shaders are available (generated by the
 * ShaderConverter tool + shaderc), they can be loaded directly for
 * better performance. Until then, source-level conversion is used.
 */
class BgfxShaderManager
{
	static var programs:Map<String, Int> = new Map();
	static var defaultProgram:Int = 0;
	static var s_tex:Int = 0;

	/**
	 * Get or create a bgfx program for the given flixel shader.
	 *
	 * Extracts GLSL source from shader metadata, converts to bgfx format,
	 * compiles via BgfxAPI.createShader, and links via BgfxAPI.createProgram.
	 *
	 * @param shader  flixel shader instance
	 * @return bgfx program handle (non-zero), or 0 on failure
	 */
	public static function get(shader:FlxShader):Int
	{
		if (shader == null)
			return getDefaultProgram();

		var key = getShaderKey(shader);
		if (programs.exists(key))
			return programs.get(key);

		// Attempt to extract and compile the shader's GLSL source
		var prog = compileFlxShader(shader);
		if (prog != 0)
		{
			programs.set(key, prog);
			return prog;
		}

		// Fallback to default pass-through program
		var fallback = getDefaultProgram();
		if (fallback != 0)
			programs.set(key, fallback);
		return fallback;
	}

	/**
	 * Get the default bgfx program (pass-through: samples texture × vertex color).
	 */
	public static function getDefaultProgram():Int
	{
		if (defaultProgram != 0) return defaultProgram;

		var vs = BgfxAPI.createShader(null);
		var fs = BgfxAPI.createShader(null);

		if (vs == 0 || fs == 0)
		{
			trace('BgfxShaderManager: WARNING — could not create default shaders');
			defaultProgram = 1;
		}
		else
		{
			defaultProgram = BgfxAPI.createProgram(vs, fs, true);
			if (defaultProgram == 0) defaultProgram = 1;
		}

		return defaultProgram;
	}

	/**
	 * Get or create the s_tex sampler uniform (texture slot 0).
	 */
	public static function getTextureSampler():Int
	{
		if (s_tex == 0)
			s_tex = BgfxAPI.createUniform("s_tex", 0, 1);
		return s_tex;
	}

	/**
	 * Attempt to compile a flixel shader into a bgfx program.
	 *
	 * Extracts GLSL source from the shader's metadata, converts it to
	 * bgfx-compatible format, and creates shaders via BgfxAPI.
	 *
	 * @return bgfx program handle, or 0 on failure
	 */
	static function compileFlxShader(shader:FlxShader):Int
	{
		try
		{
			var fragmentSrc = shader.glFragmentSource;
			var vertexSrc   = shader.glVertexSource;

			if (fragmentSrc == null || fragmentSrc.length == 0)
				return 0;

			// Extract header sources if available
			var fragmentHdr = getMetaString(shader, 'glFragmentHeader');
			var vertexHdr   = getMetaString(shader, 'glVertexHeader');

			// Combine header + source
			var fsFull = (fragmentHdr != null ? fragmentHdr + "\n" : "") + fragmentSrc;
			var vsFull = (vertexSrc != null && vertexSrc.length > 0)
				? (vertexHdr != null ? vertexHdr + "\n" : "") + vertexSrc
				: getDefaultVertexSource();

			// Convert from OpenFL GLSL to bgfx-compatible GLSL
			var fsBgfx = convertToBgfx(fsFull, "fragment");
			var vsBgfx = convertToBgfx(vsFull, "vertex");

			// Create bgfx shaders from source
			var vsHandle = BgfxAPI.createShader(createShaderMemory(vsBgfx));
			var fsHandle = BgfxAPI.createShader(createShaderMemory(fsBgfx));

			if (vsHandle == 0 || fsHandle == 0)
				return 0;

			var prog = BgfxAPI.createProgram(vsHandle, fsHandle, true);
			return prog;
		}
		catch (e:Dynamic)
		{
			trace('BgfxShaderManager: shader compilation failed — $e');
			return 0;
		}
	}

	/**
	 * Convert OpenFL-specific GLSL to bgfx-compatible GLSL.
	 *
	 * Removes OpenFL uniform declarations and attribute/varying keywords,
	 * adds bgfx_shader.sh include, and replaces input/output with $input/$output.
	 */
	static function convertToBgfx(source:String, type:String):String
	{
		var result = source;

		// Remove OpenFL-specific uniforms (bgfx provides equivalents)
		result = removeLineMatching(result, "openfl_Matrix");
		result = removeLineMatching(result, "openfl_Alpha");
		result = removeLineMatching(result, "openfl_ColorMultiplier");
		result = removeLineMatching(result, "openfl_ColorOffset");
		result = removeLineMatching(result, "openfl_HasColorTransform");
		result = removeLineMatching(result, "openfl_TextureSize");
		result = removeLineMatching(result, "openfl_TextureCoord");

		// Remove #pragma header (bgfx doesn't use it)
		result = StringTools.replace(result, "#pragma header",
			"// #pragma header (removed for bgfx)");

		// Remove attribute declarations (bgfx uses $input)
		var attrRe = ~/attribute\s+\w+\s+(\w+);/g;
		result = attrRe.replace(result, "// attribute $$1 (handled by bgfx $$input)");

		// Remove varying declarations (bgfx uses $output)
		var varyRe = ~/varying\s+(\w+\s+)(\w+);/g;
		result = varyRe.replace(result, "// varying $$2 (handled by bgfx $$output)");

		// Remove uniform sampler2D declarations (bgfx uses SAMPLER2D macro)
		result = removeLineMatching(result, "uniform sampler2D");

		// Add bgfx include if not present
		if (result.indexOf('#include <bgfx_shader.sh>') == -1)
		{
			result = '#include <bgfx_shader.sh>\n' + result;
		}

		// Ensure SAMPLER2D is used for the main texture
		if (result.indexOf('SAMPLER2D') == -1)
		{
			result = 'SAMPLER2D(s_tex, 0);\n' + result;
		}

		// Add $input/$output declarations based on type
		if (type == "vertex")
		{
			if (result.indexOf('$$input') == -1)
				result = '$$input a_position, a_texcoord0, a_color0\n' + result;
			if (result.indexOf('$$output') == -1)
				result = '$$output v_texcoord0, v_color0\n' + result;
		}
		else // fragment
		{
			if (result.indexOf('$$input') == -1)
				result = '$$input v_texcoord0, v_color0\n' + result;
		}

		return result;
	}

	static function getDefaultVertexSource():String
	{
		return
'$$input a_position, a_texcoord0, a_color0
$$output v_texcoord0, v_color0

#include <bgfx_shader.sh>

void main()
{
	gl_Position = mul(u_modelViewProj, vec4(a_position, 1.0, 1.0));
	v_texcoord0 = a_texcoord0;
	v_color0 = a_color0;
}
';
	}

	/**
	 * Create a Memory object from shader source string for BgfxAPI.createShader.
	 * When CFFI is wired, this becomes a bgfx memory buffer.
	 */
	static function createShaderMemory(source:String):Dynamic
	{
		var bytes = haxe.io.Bytes.ofString(source);
		return BgfxAPI.copy(bytes, bytes.length);
	}

	/**
	 * Try to read a metadata string from a shader instance using reflection.
	 */
	static function getMetaString(shader:FlxShader, name:String):String
	{
		try
		{
			var cls = Type.getClass(shader);
			if (cls == null) return null;
			var meta = haxe.rtti.Meta.getType(cls);
			if (meta == null) return null;
			var fields = Reflect.field(meta, name);
			if (fields == null) return null;
			var arr:Array<Dynamic> = cast fields;
			if (arr != null && arr.length > 0) return Std.string(arr[0]);
		}
		catch (e:Dynamic) {}
		return null;
	}

	/**
	 * Generate a unique cache key for a FlxShader instance.
	 */
	static function getShaderKey(shader:FlxShader):String
	{
		var className = Type.getClassName(Type.getClass(shader));
		if (className == null) className = 'Shader';
		return '$className@${shader.glFragmentSource.length}';
	}

	static function removeLineMatching(source:String, keyword:String):String
	{
		var lines = source.split("\n");
		var out:Array<String> = [];
		for (line in lines)
		{
			if (line.indexOf(keyword) == -1) out.push(line);
		}
		return out.join("\n");
	}

	/**
	 * Invalidate all cached programs (called before API switch).
	 */
	public static function invalidateAll():Void
	{
		programs.clear();
		defaultProgram = 0;
		s_tex = 0;
	}

	/**
	 * Destroy all GPU resources and clear caches.
	 */
	public static function disposeAll():Void
	{
		for (prog in programs)
			if (prog != 0 && prog != 1)
				BgfxAPI.destroyProgram(prog);

		if (defaultProgram != 0 && defaultProgram != 1)
			BgfxAPI.destroyProgram(defaultProgram);

		if (s_tex != 0)
			BgfxAPI.destroyUniform(s_tex);

		programs.clear();
		defaultProgram = 0;
		s_tex = 0;
	}
}
